- name: "Remove existing hostnames in /etc/hosts"
  blockinfile: 
    path: /etc/hosts
    insertbefore: '127.0.0.1 localhost' 
    block: ""

- name: "Update /etc/hosts with the IP/hostnames"
  blockinfile: 
    path: /etc/hosts
    insertafter: '^(.*)127.0.0.1(.*)$' 
    block: |
      127.0.0.1 localhost
      10.99.99.210 puppet puppetserver
      10.99.99.211 puppetclient

- name: Changing memory size of Java for Puppet
  shell: sed -i 's/-Xms2g -Xmx2g/-Xms250m -Xmx250m/' /etc/default/puppetserver

- name: Restart the service
  shell: sudo systemctl restart puppetserver

